name: pwd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  sqflite: ^2.3.2
  uuid: ^4.3.3
  crypto: ^3.0.0
  argon2: ^1.0.1
  collection: ^1.18.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo1.png
    - assets/images/logo2.png
